version: '3.4'
networks:
  net:
    driver: bridge
volumes:
  db_data:
  prometheus_data:
  grafana_data:
services:
    nginx:
        container_name: hostvm_nginx
        image: nginx
        depends_on:
            - web
        ports:
            - mode: host
              protocol: tcp
              published: 4000
              target: 4000
        networks:
            - net
        volumes:
            - /some/content:/usr/share/nginx/html:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    web:
        image: jeisonj2019/hostvmadmin
        container_name: hostvm_app
        depends_on:
            db:
                condition: service_healthy
        networks:
            - net
        ports:
            - 5000:5000
        environment:
            - ConnectionStrings__def=Server=hostvm_db;Port=5432;Database=hostvm;Username=postgres;Password=1234
            - ASPNETCORE_ENVIRONMENT=Development
            - Logging__Console__FormatterName=simple
            - VIRTUAL_HOST=foo.bar.com
    db:
        image: postgres
        container_name: hostvm_db
        restart: always
        environment:
          PGUSER: "postgres"
          POSTGRES_PASSWORD: "1234"
        networks:
          - net
        ports:
          - 5431:5432
        volumes:
          - db_data:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD-SHELL", "pg_isready"]
          interval: 20s
          timeout: 10s
          retries: 3
          start_period: 10s
    prometheus:
        image: prom/prometheus
        container_name: hostvm_prometheus
        depends_on:
          - web
          - db
        ports:
          - 9091:9090
        volumes:
          - ./prometheus:/etc/prometheus
          - prometheus_data:/prometheus
        user: "root"
        command: 
          --web.enable-lifecycle 
          --config.file=/etc/prometheus/prometheus.yml
        networks:
        - net
    grafana:
        image: grafana/grafana
        container_name: hostvm_grafana
        depends_on:
            - web
            - db
        ports:
          - 3001:3000
        volumes:
            - grafana_data:/var/lib/grafana
        user: "root"
        networks:
          - net 
        environment: 
            - HTTP_USER="{{grafana_user}}"
            - HTTP_PASS="{{grafana_password}}"
        restart: always
